import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; COMP=ROOT/'custom_components/freshairiq'
FLOW=(COMP/'config_flow.py').read_text(); CARD=(COMP/'frontend/freshairiq-card.js').read_text(); COORD=(COMP/'coordinator.py').read_text()
def test_optional_selectors_use_suggested_value_not_default_so_clear_persists():
    block=FLOW[FLOW.index('def _optional'):FLOW.index('def _time_default')]
    assert 'suggested_value' in block
    assert 'default=value' not in block
    assert 'CONF_ROOM_ILLUMINANCE' in FLOW

def test_room_and_goal_order_show_complete_ranked_forms():
    assert 'room_position_{idx}' in FLOW
    assert 'goal_priority_{idx}' in FLOW
    assert 'room_to_move' not in FLOW and 'goal_to_move' not in FLOW
    assert 'wizard_back' in FLOW

def test_details_and_support_mobile_layout_fixes():
    assert 'grid-template-columns:42px minmax(0,1fr) 42px;align-items:center' in CARD
    assert '#ventlog-export{margin-left:auto}' in CARD
    assert 'class="support-email"' in CARD
    assert 'Ändern unter Geräte & Dienste → FreshAirIQ → Konfigurieren → Daten & Lernen → Diagnose-Freigabe.</span></div><span class="muted">' not in CARD

def test_blocked_copy_is_explanatory():
    # 0.26.2.14: blocked goals are explained in plain language (not an error).
    assert 'gerade nicht durch Lüften erreichbar' in CARD
    assert 'derzeit blockiert' not in CARD

def test_cover_position_interpretation_is_available_at_opening_and_runtime_uses_room_override():
    assert 'vol.Required("cover_position_zero_means"' in FLOW
    assert 'room.get("cover_position_zero_means", options.get("cover_position_zero_means"' in COORD

def test_resident_profiles_are_structured_not_raw_json_editor():
    block=FLOW[FLOW.index('def _residents_schema'):FLOW.index('def _forecast_schema')]
    assert 'selector.TextSelector(selector.TextSelectorConfig(multiline=True))' not in block
    assert 'adult_1_rooms' not in block  # generated by role/index, not hard-coded raw JSON
    assert 'profile_fields' in block and '_notifications' in block and '_thermal' in block

def test_german_room_copy_is_localized_and_documented():
    de=json.loads((COMP/'translations/de.json').read_text())
    step=de['options']['step']['edit_room']
    for key in ('co2','exhaust_fan','climate','target_temperature_mode','target_temperature','target_temperature_fallback'):
        assert step['data'][key] != key
        assert step['data_description'][key]
